---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
library(leaflet)

seabirds <- read_csv("data/seabirds_cleaned.csv")
```
```{r}
head(seabirds)

seabirds %>% 
  filter(str_detect(species_common, "Royal albatros"))
```
```{r}
# We want a stacked bar of most common and most rare birds

#filter for rarest birds:
birds_rare <- seabirds %>% 
  select(species_scientific, species_common, species_abbreviation, count) %>%
  filter(!str_detect(species_common, "sensu lato")) %>% 
  filter(str_detect(species_scientific, "[A-Z]{1}[a-z]* [a-z]*$")) %>% 
  filter(!str_detect(species_common, "unidentified")) %>% 
  filter(!str_detect(species_scientific, "\\/")) %>% 
  group_by(species_scientific, species_common, species_abbreviation) %>% 
  summarise(count_individual_birds = sum(count)) %>% 
  arrange(count_individual_birds) %>% 
  # now you only have the rarest birds ever seen.
  head(7)



#filter for most common birds:
birds_common <-   seabirds %>% 
  select(species_scientific, species_common, species_abbreviation, count) %>%
  filter(!str_detect(species_common, "sensu lato")) %>% 
  filter(str_detect(species_scientific, "[A-Z]{1}[a-z]* [a-z]*$")) %>% 
  filter(!str_detect(species_common, "unidentified")) %>% 
  filter(!str_detect(species_scientific, "\\/")) %>% 
  group_by(species_scientific, species_common, species_abbreviation) %>% 
  summarise(count_individual_birds = sum(count)) %>% 
  arrange(desc(count_individual_birds)) %>% 
  # now you only have the most common birds
  head(7)

#now create plots, most common
plot_birds_common <- birds_common %>% 
  ggplot() +
  aes(x = species_common, y = count_individual_birds) +
  geom_col(fill = "#addd8e") +
  coord_flip() +
  ylab("Total individual birds observed") +
  xlab("") +
  ggtitle("Most common birds seen") +
  theme_classic() +
  scale_y_continuous(labels = scales::comma)

ggplotly(plot_birds_common)

#now create plots, most rare

plot_birds_rare <- birds_rare %>% 
  ggplot() +
  aes(x = species_common, y = count_individual_birds) +
  geom_col(fill = "#e34a33") +
  coord_flip() +
  ylab("Total individual birds observed") +
  xlab("") +
  ggtitle("Rarest birds observed") +
  theme_classic() +
  scale_y_continuous(breaks = 1:5) +
  expand_limits(y = 5)

ggplotly(plot_birds_rare)
  
 
```

```{r}
# sparkline for total bird species observed

seabirds %>% 
  mutate(year = lubridate::year(date)) %>% 
  select(species_scientific, species_common, species_abbreviation, year) %>% 
  filter(!str_detect(species_common, "sensu lato")) %>% 
  filter(str_detect(species_scientific, "[A-Z]{1}[a-z]* [a-z]*$")) %>% 
  filter(!str_detect(species_common, "unidentified")) %>% 
  filter(!str_detect(species_scientific, "\\/")) %>% 
  select(year, species_scientific) %>% 
  group_by(year) %>% 
  summarise(total_species_per_year = n()) %>% 
  mutate(label_text = ifelse(year == 1990, total_species_per_year, NA)) %>% 
  ggplot() +
  aes(x = year, y = total_species_per_year) +
  geom_line(colour = "#08519c") +
  geom_area(fill = "#9ecae1") +
  geom_point(colour = "#08519c", size = 4) +
  geom_text(aes(label = label_text), hjust = -0.5, size = 8) +
  theme_void() +
  expand_limits(x = 1991) +
  ggtitle("Total species observed in recent years")



```
```{r}
#area with royal albatros sightings!

seabirds %>% 
  filter(str_detect(species_common, "Royal albatros")) %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$OpenStreetMap) %>% 
  addMarkers(lng = ~long, lat = ~lat, popup = ~species_scientific)
  


```

