---
title: "R Notebook"
output: html_notebook
---

# Homework weekend review Week 1

#1 How many books in each language?
```{r}
library(tidyverse)
books <- read_csv("data/books.csv")
```
```{r}
books %>% 
  group_by(language_code) %>% 
  summarise(num_of_books = n()) %>% 
            arrange(desc(num_of_books))
)

# or quicker:
books %>% 
  count(language_code)
```

# Any similarities between top rated books?

```{r}
purged <- books %>% 
  #select(authors) %>% 
  filter(!authors == "NOT A BOOK")
  

purged %>% 
  filter(ratings_count >= 100) %>% 
  slice_max(average_rating, n = 5)
```

# more recent books higher score than older? (see my own script)
```{r}
books %>% 
  filter(ratings_count > 1) %>% 
  select(title, authors, publication_date, average_rating) %>% 
  mutate(new_pub_date = as.Date(publication_date, "%m/%d/%Y")), 
.before = publication_date)
  
books %>% 
filter(is.na(year))

# NA's are instoduced because the date format is different notation than the rest.
```
# Which languages has JK Rowling published in

```{r}
books %>% 
  select(authors, language_code) %>% 
  mutate(JK = str_detect(authors, "J.K. Rowling"), 
         .after = authors) %>% 
  filter(JK == TRUE) %>% 
  distinct(language_code)


```

# Is there missing data in the dataset
```{r}
books %>% 
  summarise(across(.cols = everything(), 
                   .fns = ~sum(is.na(.x)))
            )
```

